### ISSUE TITLE
From command line, max count collection sometimes doesn't appear to stop?

### ISSUE THREAD

**Issue by psychemedia** [Jefferson-Henrique/GetOldTweets-python#10]
On occasion, with a largish number of max_tweets and a search range way in the past, the command line utility appears to get stuck (or maybe twitter is slowing down how quickly it returns pages).

Might it be worth trying to be more defensive on how you break out of the `while True` collection loop? Or perhaps appending tweets to the export file as you go along (eg save in batches of every 100 or so)?

**Comment by Jefferson-Henrique** [comment]
Thanks @psychemedia, you are totally right, thanks for you idea, I will implement this soon.

**Comment by Jefferson-Henrique** [comment]
I have done it, now for each bunch of 100 tweets a flush is executed (and I put a log to give some idea of life hahah).
