### ISSUE TITLE
How to correctly get more than one tweet

### ISSUE THREAD

**Issue by mauroJoestar** [Jefferson-Henrique/GetOldTweets-python#104]
Hi. I'm facing issues when i'm getting more than one tweet. The maximum number of tweets that i can get is 500 and it tooks like 5 hours to do that. Is there something wrong with my code? How can I get more tweets in less time?

```
import got
import csv
import unicodecsv as csv

max_tweets = 500

tweetCriteria = got.manager.TweetCriteria().setSince("2017-05-01").setUntil("2017-07-31").setQuerySearch("danonino").setMaxTweets(max_tweets)
# Open/Create a file to append data
csvFile = open('dataset_tweets.csv', 'a')
#Use csv Writer
csvWriter = csv.writer(csvFile)
for i in range(max_tweets):
    tweet = got.manager.TweetManager.getTweets(tweetCriteria)[i]
    print i
    csvWriter.writerow([tweet.id, tweet.date, tweet.username, tweet.text])

```

**Comment by als5ev** [comment]
```tweet = got.manager.TweetManager.getTweets(tweetCriteria)[i]``` 

This line inside the for loop is the issue. This line returns a list of all the tweets. Your current code is scraping twitter and building that list 500 times. 


Move the line outside your for loop and iterate through the ```tweet``` object to get same functionality.

**Comment by als5ev** [comment]
Can this be closed?

**Comment by mauroJoestar** [comment]
Thanks now it works very well!
