### ISSUE TITLE
Can only download last weeks data

### ISSUE THREAD

**Issue by kristofersen** [Jefferson-Henrique/GetOldTweets-python#133]
This might be a twitter issue, but it looks like this only is working to download the last weeks worth of data. Can anyone verify this?

**Comment by hemogre** [comment]
Hello,

I just tried and I have no problem to get all the data I want.
What kind of request did you do?

**Comment by kristofersen** [comment]
Thanks for looking at this. I ended up trying from a different location and it works. I think my IP might have been blocked. :\ I'll close the issue.
