### ISSUE TITLE
CSV only contains nth tweet instead of all the tweets 

### ISSUE THREAD

**Issue by Mohammedtheorator** [Jefferson-Henrique/GetOldTweets-python#144]
# The code is meant to download 10 tweets about Trump and export them into a csv file in my documents folder. 

When I run it, 10 tweets are downloaded but the 10th tweet is the only one that shows up in the csv file. 

Anybody else have this problem or know how to fix it?

Thank you for your time, much appreciated.

![code](https://user-images.githubusercontent.com/31608171/35459560-aa76a9d6-02ae-11e8-80e4-999a68c81393.PNG)

**Comment by egandunning** [comment]
This worked for me:
![got](https://user-images.githubusercontent.com/11324606/35466214-960c71e4-02b6-11e8-815c-cbd70996867b.png)

I'm not sure why your code doesn't work, but I copied this from Exporter.py, and it saves all 10 tweets.

**Comment by Mohammedtheorator** [comment]
Thank you!

**Comment by Jefferson-Henrique** [comment]
Hi @Mohammedtheorator, you code is almost right but your "tweetwitter" is being used outside the for's context, so after the for is over the "tweet" variable is related to the nth (last) tweet in your list.

**Comment by Mohammedtheorator** [comment]
Thank you @Jefferson-Henrique I was able to use the exporter to get what I needed done. 

ps
The setTopTweet criteria mostly gets german tweets when I use it. Do I also need to set geolocation when using the TopTweet criteria?
