### ISSUE TITLE
Tweet manager retweet error

### ISSUE THREAD

**Issue by Mohammedtheorator** [Jefferson-Henrique/GetOldTweets-python#148]
**I am currently attempting to build a database of tweets so I can plot a time series graphs of the sentiment.** 

Below is an example of my query and date boundaries.
` tweetCriteria = got.manager.TweetCriteria().setQuerySearch("Trump").setSince("2018-1-10").setUntil("2018-1-12")`

The problem is that after downloading about 13KB of data I get this error and the download process stops.
retweets = int(tweetPQ("span.ProfileTweet-action--retweet span.ProfileTweet-actionCount").attr("data-tweet-stat-count").replace(",", ""));
AttributeError: 'NoneType' object has no attribute 'replace'

Has anyone else come across this problem? know how to fix it? 

Thank you!

**Comment by hariskr** [comment]
Same issue... have you found a solution yet? Would breaking up the data collection into smaller time windows help?

**Comment by Mohammedtheorator** [comment]
@hariskr 
It happens randomly for me. It only came up once in the last few weeks though. I can't remember what kind of error it raises but you can use the method below to ignore the error and continue the code. You may need to change the "BaseException" to the exception that handles that error. 

` **try:**  
        YOUR CODE 
    **except BaseException as exception:**`
