### ISSUE TITLE
Top tweets pulls German tweets only

### ISSUE THREAD

**Issue by Mohammedtheorator** [Jefferson-Henrique/GetOldTweets-python#149]
I was thinking about only pulling top tweets regarding the subject I am interested in performing sentiment analysis on. Pulling these kinds of tweets will express sentiment among influencers. This can be a powerful and time-saving feature, but I have no luck with it so far. Every time I use it, a majority of the tweets I pull are in German even though I was searching for top tweets about Trump.

 Any help with this issue would be much appreciated.

**Comment by StefanoMartin** [comment]
I solved this problem by modifying the file /got/manager/TweetManager.py

At line 106 there should be a line like this: 
"https://twitter.com/i/search/timeline?q=%s&src=typd&max_position=%s"

To have the tweets in English, you can modify this line like this:
"https://twitter.com/i/search/timeline?q=%s&l=en&src=typd&max_position=%s"

Probably for other language you can play by changing "en" with another language.

Let me know if this solve your issue too.
