### ISSUE TITLE
getting JSON from Tweet Status is possible?

### ISSUE THREAD

**Issue by dogdrip2848** [Jefferson-Henrique/GetOldTweets-python#16]
first of all, thank you for your code, it helped me a lot!

what I'm trying to do is to get tweet status as JSON format to get mentions on my twitter.

is it possible to bypass Twitter API with your embed twitter querying method for this case?
("https://twitter.com/i/search/timeline?f=realtime&q=%s&src=typd&max_position=%s")

I'm just trying to parse HTML down with regular expressions right now, but it is not working out smoothly.

**Comment by Jefferson-Henrique** [comment]
I don't know exactly, you can check which request twitter is doing to get what you want. Did you do some advance on this?

**Comment by dogdrip2848** [comment]
not yet, still working on it

**Comment by mehdismh24** [comment]
@dogdrip2848 Is there any progress on this issue?
