### ISSUE TITLE
Possible to tell if a tweet is a reply?

### ISSUE THREAD

**Issue by eagren20** [Jefferson-Henrique/GetOldTweets-python#169]
You used to be able to tell if a tweet was directed at somebody because the tweet body would start with the recipient's twitter handle. However, in 2016 Twitter changed the reply system so that the handles you're replying to are tweet metadata instead of in the actual body of the tweet. Is there a way either through GetOldTweets or the Twitter API to tell if tweets from after the change are a reply or regular tweet?

**Comment by serdasteclas** [comment]
I managed to get this working by adding this piece of code on line 55 at TweetManager.py:
```
tweet.isReply = tweetPQ("div.ReplyingToContextBelowAuthor").is_("div")
if tweet.isReply:
	tweet.replyTo = tweetPQ("div.ReplyingToContextBelowAuthor span.username b").contents()[0]
else:
	tweet.replyTo = ''
```

**Comment by Jrbt** [comment]
This is extremely helpful, thank you. However, if I run the grab now, I get the same output file as before with 10 columns and no way of identifying replies. Do I have to set some parameter in my request to include/exclude replies or get more information in the output?

**Comment by malidzanko** [comment]
@Jrbt  and anyone else who might come across this issue, I simply added this line to check if it is a reply 

`if (tweetPQ("div").attr("data-is-reply-to")=="true")`

**Comment by deldar22** [comment]
@malidzanko Where did you add that line of code?

**Comment by malidzanko** [comment]
@deldar22 anytime after the line `tweetPQ = PyQuery(tweetHTML)` is fine. I added some more code so the exact line won't mean much to you. Also, been a while since I've used this module so can't guarantee it still works. Good luck!

**Comment by deldar22** [comment]
I tried this but it didn't work around line 34, are you able to see the error: 

	for tweetHTML in tweets:
				tweetPQ = PyQuery(tweetHTML)
				tweet = models.Tweet()
				if (tweetPQ("div").attr("data-is-reply-to")=="true"):
					pass
				else: 
					usernameTweet = tweetPQ("span.username.js-action-profile-name b").text()
					txt = re.sub(r"\s+", " ", tweetPQ("p.js-tweet-text").text().replace('# ', #').replace('@ ', '@'))
					retweets = int(tweetPQ("span.ProfileTweet-action--retweet span.ProfileTweet-actionCount").attr("data-tweet-stat-count").replace(",", ""))
					favorites = int(tweetPQ("span.ProfileTweet-action--favorite span.ProfileTweet-actionCount").attr("data-tweet-stat-count").replace(",", ""))
					dateSec = int(tweetPQ("small.time span.js-short-timestamp").attr("data-time"))
					id = tweetPQ.attr("data-tweet-id")
					permalink = tweetPQ.attr("data-permalink-path")
					user_id = int(tweetPQ("a.js-user-profile-link").attr("data-user-id"))

**Comment by abushoeb** [comment]
@deldar22 @serdasteclas hi guys, is it possible to get all replies if a tweet has any replies? Many thanks in advance.
