### ISSUE TITLE
Only fetching Top results

### ISSUE THREAD

**Issue by njharbo** [Jefferson-Henrique/GetOldTweets-python#18]
Great work! 

I had to change the url in TweetManager.py to:
url = "https://twitter.com/i/search/timelinef=tweets&vertical=default&q=%s&src=typd&max_position=%s"

Using the original url, I only got the "Top" results from the search - not the "Live" ones. 

Maybe twitter changed the http-address?

I am happy to push the corrected version if you wish?

Again thanks a lot for providing this great program!

**Comment by Jefferson-Henrique** [comment]
Humm very nice catch @njharbo, I will merge a pull request to offer this as a option on TwitterCriteria. Thanks for you reply!

**Comment by njharbo** [comment]
Great! Thanks for answer. I have submitted a pull request.

**Comment by njharbo** [comment]
I see that  @ddandur make a much nicer solution to this problem. Thus, I have closed my pull request. Thanks!
