### ISSUE TITLE
filter query over minimum or maximum likes and retweets

### ISSUE THREAD

**Issue by trenkert** [Jefferson-Henrique/GetOldTweets-python#183]
Is it possible to do a query search that filters over the number of likes and/or retweets?

like: 

`python Exporter.py --querysearch "europe refugees" --minlikes 10 --minretweets 5 
`
or

`python Exporter.py --querysearch "europe refugees" --maxlikes 1 --maxretweets 0
`

**Comment by Jefferson-Henrique** [comment]
Hi @trenkert, it don't seem to be possible using Twitter Advanced Search, so it will no be possible to use with GOT.
