### ISSUE TITLE
Script Doesn't Work Right Now

### ISSUE THREAD

**Issue by abdullahonden** [Jefferson-Henrique/GetOldTweets-python#188]
This script doesn't seem to be working right know. Is says "Twitter weird response". JSON file still coming from Twitter.com, possibly the syntax or something is changed. Do you have any ideas how to fix the issue?

Thanks..

**Comment by abdullahonden** [comment]
It returns: ('Unexpected error:', <class 'urllib2.HTTPError'>)

**Comment by abdullahonden** [comment]
Here's the page that Twitter returns:


  | <?xml version="1.0" encoding="utf-8"?>
-- | --
  | <!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.1//EN" "http://www.openmobilealliance.org/tech/DTD/xhtml-mobile11.dtd">
  | <html xmlns="http://www.w3.org/1999/xhtml">
  | <head>
  | <meta name="HandheldFriendly" content="True" />
  | <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
  |  
  | <meta name="twitter-redirect-url" content="twitter://timeline"/>
  | <meta name="twitter-redirect-srcs" content="{&quot;pwreset-iphone&quot;:true,&quot;android&quot;:true,&quot;email&quot;:true}"/>
  | <link href="https://ma.twimg.com/twitter-mobile/8f3445bd0e5eb63b939e25a6ff29981d947a4a51/images/favicon.ico" rel="icon" type="image/x-icon" />
  | <title>Twitter</title>
  | <link href="https://ma.twimg.com/twitter-mobile/8f3445bd0e5eb63b939e25a6ff29981d947a4a51/assets/sys.css" media="screen" rel="stylesheet" type="text/css" />
  | <meta name="google-site-verification" content="V0yIS0Ec_o3Ii9KThrCoMCkwTYMMJ_JYx_RSaGhFYvw" />
  | <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0">
  | </head>
  | <body class="images nojs">
  | <div id="container">
  |  
  | <div id="brand_bar" class="chromeless">
  | <table id="top">
  | <tr>
  | <td class="modal-left">
  | <a href="/" class="brandmark">
  | <img src="https://ma.twimg.com/twitter-mobile/8f3445bd0e5eb63b939e25a6ff29981d947a4a51/images/larrybird_white.png" class="brandmark_larry" alt="Twitter" width="18" height="15" />
  | </a>
  | <span class="title">Twitter</span>
  | </td>
  | <td class="modal-right">
  | </td>
  | </tr>
  | </table>
  | </div>
  |  
  |  
  |  
  | <div id="main_content">
  | <div class="system">
  | <div class="blue">
  | <table class="content">
  | <tr>
  | <td>
  | <div class="title">Sorry, diese Seite existiert nicht</div>
  | <div class="subtitle"><a href="/">Zurück zur Startseite</a></div>
  | </td>
  | </tr>
  | </table>
  | </div>
  | </div>
  |  
  | </div>
  | <div id="footer">
  | <div class="search-fields">
  | <div class="title">
  | <label for="q">Gib ein Thema, einen @Nutzernamen oder Vor- und Nachnamen ein</label>
  | </div>
  | <form action="/search" class="search-input" method="get">
  | <table>
  | <tr>
  | <td class="value" id="search"><div><input id="q" name="q" type="text" value=""/></div></td>
  | <td class="button">
  | <input type="hidden" name="s" value="typd" />
  | <input type="image" src="https://ma.twimg.com/twitter-mobile/8f3445bd0e5eb63b939e25a6ff29981d947a4a51/images/sprites/magnifying_glass.gif" alt="Suchen"/>
  | </td>
  | </tr>
  | </table>
  | </form>
  | </div>
  |  
  | <div class="view-actions"><a href="#top">Zurück nach oben</a> &middot; <a href="/settings/profile_images">Bilder ausblenden</a></div>
  | </div>
  |  
  | </div>
  | <script src="https://ma.twimg.com/twitter-mobile/8f3445bd0e5eb63b939e25a6ff29981d947a4a51/assets/base.js" type="text/javascript"></script>
  |  
  | <img src="/i/anonymize?data=%5B%7B%22integration%22%3A%22ga%22%2C%22ref%22%3A%22https%3A%5C%2F%5C%2Ftwitter.com%5C%2Fi%5C%2Fsearch%5C%2Ftimeline%3Ff%3Dtweets%26q%3D%2520from%253Aoneplus%2520since%253A2018-01-01%2520until%253A2018-03-31%26src%3Dtypd%26max_position%3D%26l%3Den%22%2C%22mobileMetricsToken%22%3A%22152699540123518213%22%7D%5D" height="0" width="0" style="opacity: 0">
  |  
  | </body>
  | </html>

**Comment by oxygala** [comment]
I can confirm that the script stopped working.

**Comment by abdullahonden** [comment]
I think Twitter added a redirect or smth to get the JSON. I can get the file from browser, but script can't download it so it doesn't work.

**Comment by stefanstrueder** [comment]
Stopped working for me too. @abdullahonden Can you tell me how to get the JSON file from browser?

**Comment by abdullahonden** [comment]
I've sent a pull-request with the fix:
https://github.com/Jefferson-Henrique/GetOldTweets-python/pull/189

**Comment by heenaI** [comment]
Thanks @abdullahonden your fix solved the issue for now

**Comment by Jefferson-Henrique** [comment]
Hi guys, interesting finding @abdullahonden, I just found the same issue running by my own. Thanks for sharing anyway.

**Comment by heenaI** [comment]
it still does not work for more then 1000 tweets for me
