### ISSUE TITLE
Repeated tweets

### ISSUE THREAD

**Issue by meiyougithub** [Jefferson-Henrique/GetOldTweets-python#2]
Hi! 
Thanks a lot for creating this amazing project!

When I ran the codes in Main.py, I found that the collected tweets would be repeated if the "maxtweets">30. For instance, 21st - 40 th tweets would be exactly the same as the first 20 tweets, including the time.

Am I missing some important codes so that I got the problem?

Thanks!

**Comment by Jefferson-Henrique** [comment]
Hello, I have noticed this bug, but I think I have fixed it. Do you have the last version? If yes can you say to me which parameters you used so I can reproduce your query?

**Comment by meiyougithub** [comment]
Thanks! I will download the latest version and have a try.

Here are the parameters I used:
setQuerySearch('hair').setUntil("2016-02-20").setMaxTweets(100)

**Comment by Jefferson-Henrique** [comment]
Nicee, you're welcome. I have removed some chars to avoid some charset errors, you can change this line:
https://github.com/Jefferson-Henrique/GetOldTweets-python/blob/master/got/manager/TweetManager.py#L32

**Comment by manoharlax** [comment]
Hi Jefferson-Henrique, I am facing the same issue mentioned by meiyougithub. Can you please help me out ?

**Comment by manoharlax** [comment]
I am getting all the tweets now! It was the version issue as you had mentioned earlier. Thanks!
