### ISSUE TITLE
gives empty csv file

### ISSUE THREAD

**Issue by dogdrip2848** [Jefferson-Henrique/GetOldTweets-python#20]
hi, there is another issue.

in some cases, your code only gives empty (not exactly empty, just header) CSV file.

I looked into it, there are 2 cases.

one is a person who hasn't tweeted for a long time. and another is maybe IP-ban cases, I used this code to crawl some organizations twitters, and gives empty CSV files sometimes.

are there any way to avoid this cases? especially the first one - long-time-no-tweet

**Comment by Jefferson-Henrique** [comment]
Hi @dogdrip2848, well I didn't noticed this yet, I am very lucky with my ISP I never face these problems when I am testing it :/. I will take a look but right now I don't how overpass that.

**Comment by Sindhu-Kiranmai** [comment]
Hey. Same issue here. 
I am trying to fetch tweets by username within a bounded period of time. It returns an empty csv with just the header. Any fix to this issue?

**Comment by Jefferson-Henrique** [comment]
hello @Sindhu-Kiranmai , I don't know what exactly causes that, but here I get all the results without any problems, some people face the same issue as you and others don't.

**Comment by Sindhu-Kiranmai** [comment]
Hi @Jefferson-Henrique Thanks.
Is there a rate limit imposed even while crawling on twitter? Do you think that might cause an issue?

**Comment by chandrasg** [comment]
Yes, I faced a similar issue - this seems to be a rate limit imposition. When I retry after a prolonged wait, it works again.
