### ISSUE TITLE
No idea what the error is about :(

### ISSUE THREAD

**Issue by coolsandeee** [Jefferson-Henrique/GetOldTweets-python#21]
I have installed both lxml and pyquery on windows 10.
Used this command at the command prompt. Python installation directory is created in the path. 

python Exporter.py --username 'barackobama' --maxtweets 1
  File "Exporter.py", line 8
    print 'You must pass some parameters. Use \"-h\" to help.'
                                                             ^
SyntaxError: Missing parentheses in call to 'print'

Kindly help me resolve this issue.

**Comment by Jefferson-Henrique** [comment]
Which is your Python version?

**Comment by coolsandeee** [comment]
Hi. It is 3.4.4

**Comment by coolsandeee** [comment]
Btw, I have downloaded the Java version of this and it is works for me. Thank you for that one. Also, I would want to try out the python one too.
