### ISSUE TITLE
Query search in a time slot always return same group of tweets

### ISSUE THREAD

**Issue by lingchen0331** [Jefferson-Henrique/GetOldTweets-python#218]
When I try to search tweets in a certain topic in a given time slot, it always returns the same group of tweets no matter what the 'maxtweets' is. I am wondering if anyone has the same issue.
For example, when I use the follow command to search, it always return the same 20 tweets over and over, and it is also different from the twitter advanced search page.
`python Exporter.py --querysearch 'europe refugees' --since 2016-10-13 --until 2016-10-17 --maxtweets 100`

Thanks for your code! @Jefferson-Henrique

**Comment by Mottl** [comment]
Duplicate. Original issue is https://github.com/Jefferson-Henrique/GetOldTweets-python/issues/217

**Comment by lingchen0331** [comment]
Thanks! @Mottl
