### ISSUE TITLE
dowload repeated tweet with same date

### ISSUE THREAD

**Issue by humasak** [Jefferson-Henrique/GetOldTweets-python#222]
Hi!
Thanks a lot for creating this amazing project!

When I ran the codes in Main.py, I found that the collected tweets would be repeated with the date. It seems like only download some tweets and the program is always run (never stop). The collected tweet reach more than hundreds MB but it is an identical tweet with a similar date. 

For example: python2 Exporter.py --near "Birmingham,England" --within 50mi --since 2018-10-30 --until 2018-10-31

the example result that I got:

username;date;retweets;favorites;text;geo;mentions;hashtags;id;permalink
fallinkissy;2018-10-30 23:59;0;1;"always knew you had a thing for older men";;;;"1057421891441442816";https://twitter.com/fallinkissy/status/1057421891441442816
itz_hayz;2018-10-30 23:59;1;8;"twerk twerkhttps://twitter.com/canwetalkbrad/status/1057297614335545344 …";;;;"1057421883480645633";https://twitter.com/itz_hayz/status/1057421883480645633
---
---
---
---
fallinkissy;2018-10-30 23:59;0;1;"always knew you had a thing for older men";;;;"1057421891441442816";https://twitter.com/fallinkissy/status/1057421891441442816
itz_hayz;2018-10-30 23:59;1;8;"twerk twerkhttps://twitter.com/canwetalkbrad/status/1057297614335545344 …";;;;"1057421883480645633";https://twitter.com/itz_hayz/status/1057421883480645633

So the result only 22 different tweets and it's repeated (not stop) until reaching more than hundreds MB or GB.  Furthermore, the date is always 2018-10-30 23:59
Am I missing some important codes so that I got the problem? or is the program banned by twitter?

**Comment by Mottl** [comment]
Duplicate: https://github.com/Jefferson-Henrique/GetOldTweets-python/issues/217

**Comment by humasak** [comment]
thanks..I just read it. My problem solve.
