### ISSUE TITLE
Setting the timeframe doesn't work anymore

### ISSUE THREAD

**Issue by patsbin** [Jefferson-Henrique/GetOldTweets-python#224]
The second example doesn't work anymore. setUntil and setSince produce some failure.

tweetCriteria = got.manager.TweetCriteria().setQuerySearch('europe refugees').setSince("2015-05-01").setUntil("2015-09-30").setMaxTweets(1)
tweet = got.manager.TweetManager.getTweets(tweetCriteria)[0]

Traceback (most recent call last):
  File "Main.py", line 36, in <module>
    main()
  File "Main.py", line 25, in main
    tweet = got.manager.TweetManager.getTweets(tweetCriteria)[0]
IndexError: list index out of range

**Comment by varshavijaykumar22** [comment]
Facing the same issue, only 20 tweets are being retrieved and later its duplicated.

**Comment by Jefferson-Henrique** [comment]
Can you pull and check again @patsbin ?

**Comment by patsbin** [comment]
Everything works fine again. But also in my old project. Looks like this was a temporary change on the twitter website maybe?
