### ISSUE TITLE
only returning tweets for last week?

### ISSUE THREAD

**Issue by dogdrip2848** [Jefferson-Henrique/GetOldTweets-python#23]
I found out yesterday that Exporter.py is not giving back actual "all tweets".

for your example, I crawled twitter with username 'barackobama' without other options such as 
'maxtweet', it gives the only handful of 25 tweets  starting from a week ago. 

maybe this code detected and blocked?

**Comment by dogdrip2848** [comment]
P.S. I've set "alltweets" options to "True",

**Comment by zhutourou** [comment]
Hi dogdrip2848,

search in twitter.com, you may see the real problem.
