### ISSUE TITLE
querysearch problem

### ISSUE THREAD

**Issue by zhutourou** [Jefferson-Henrique/GetOldTweets-python#24]
Thanks for your job, Jefferson. I really need it right now. but it does not work normally in commend line.

When I input  Exporter.py --querysearch '#microsoft' --since 2016-01-01 --until 2016-01-31 --maxtweets 0

I got part of the tweets not all of that, usually less than two days period ending in 2016-01-31. Can you help with it.

**Comment by Jefferson-Henrique** [comment]
Hello @zhutourou, it was supposed to work, some guys bypass these problems changing ISP, I did the same search as you here and it works fine, if you need this data for some research I can get here for you and send over email.
