### ISSUE TITLE
Encoding issue with french special characters (Accents)

### ISSUE THREAD

**Issue by ilyeskabbourim** [Jefferson-Henrique/GetOldTweets-python#243]
Great work, i have an issue with extracting tweets in french, espcially with the encoding. I don't get accents in french. Instead I get @!
Is there an argument to add or a particular encoding that would fix this issue  ?

Thank you.

**Comment by giovsta** [comment]
may I ask how you solved this? I have the same issue with Italian. sorry for reopening an old post!
