### ISSUE TITLE
A way to authenticate in order to search private users?

### ISSUE THREAD

**Issue by TPhiz** [Jefferson-Henrique/GetOldTweets-python#25]
Hello,

Is it possible to add a way to "log in" with an account and search users' tweets that are protected from unapproved followers?

Thanks!

**Comment by Jefferson-Henrique** [comment]
Yes, I think it is possible, I was thinking about too it is a useful feature to access some restrict information, but I think I will not implement this soon. Thanks for the idea.

**Comment by TPhiz** [comment]
Good to know that you think it's possible. I'll try and look into it... Love what you guys have created so far.

**Comment by Jefferson-Henrique** [comment]
Thanks @TPhiz =D.
