### ISSUE TITLE
Basic help to use this - like a dummies example

### ISSUE THREAD

**Issue by drizham** [Jefferson-Henrique/GetOldTweets-python#27]
Hi there,
I am no Python pro but would like to use this package.  I've cloned the repo and navigated to the folder. I then launched it with

> python Export.py --username 'barackobama' --since 2015-09-10 --until 2015-09-12 --maxtweets

I get the following error:
  File "Exporter.py", line 6
    print 'You must pass some parameters. Use \"-h\" to help.'
                                                             ^
SyntaxError: Missing parentheses in call to 'print'

Can someone show me a simple example of using this?
Thanks

**Comment by gittyjosh** [comment]
Looks like you're along the right lines. Where you've written `--maxtweets` you should specify a number after, otherwise if you want all tweets you don't need --maxtweets in there. 

which version of python are you using? this error could be caused by using 3.x. GetOldTweets runs in 2.7

**Comment by ogencoglu** [comment]
The print statement has been replaced with a print() function in python 3. You need parenthesis if you use python 3.x.

**Comment by Jefferson-Henrique** [comment]
Thanks @gittyjosh  and @ogencoglu for your help on this.

**Comment by drizham** [comment]
Thank you so much, guess I'll be installing a Python 2.7 to get this working!
