### ISSUE TITLE
Filter tweets by language

### ISSUE THREAD

**Issue by pedrohenrique13** [Jefferson-Henrique/GetOldTweets-python#28]
Hi

How can I filter tweets by language?

**Comment by Jefferson-Henrique** [comment]
Hello @pedrohenrique13, I didn't expose this on api but it is a good point. In your querysearch parameter you can use something like this ' "--querysearch "for the win lang:pt" '.

"lang:pt" should filter by portuguese language. All options avaliable on this page [Twitter Advanced Search](https://twitter.com/search-advanced) can be used.

**Comment by Vichoko** [comment]
@Jefferson-Henrique Hello Jefferson, i'm trying to use the option "Any of this words" of the Advanced Search. In this case i should just separate the words i want with colons? Or should i put an option before?
