### ISSUE TITLE
Clarification:

### ISSUE THREAD

**Issue by ksk438** [Jefferson-Henrique/GetOldTweets-python#29]
It seems that the output  ( I used: python Exporter.py --username 'barackobama' --maxtweets 100) returns tweets by other users @barackobama instead of tweets by barackobama. Is it possible to get tweets by the user using this?

**Comment by Jefferson-Henrique** [comment]
Hi @ksk438, thanks for your issue, it seems that twitter changed a little bit the search behavior, you can try without quotes that you get your desired results (python Exporter.py --username barackobama --maxtweets 100). I will fix it in the code next update.

**Comment by Jefferson-Henrique** [comment]
I have updated the repo @ksk438, now it should work fine even with quotes.

**Comment by ksk438** [comment]
Great! Will take a look when I have a moment
