### ISSUE TITLE
setSince and setUntil issue

### ISSUE THREAD

**Issue by mcalistj** [Jefferson-Henrique/GetOldTweets-python#3]
I think Twitter may have determined that I had been abusing their service. Yesterday, I ran your program to collect over 20,000 tweets. It ran fine. Each call involved a setSince and setUntil date and setMaxTweets to 10.

Today I changed it setMaxTweets to 20. It worked for the first 10 calls or so and then stopped. I had modified your programming to carry out some pre and post-processing. I resorted back to original copy, latest version, and from what I can see it is not returning anyway tweets which have dates specified in the tweetCriteria. Have you ever encountered it? Any tips? I will try it from a different ip address later 

The error is as follows:
Traceback (most recent call last):
  File "Main.py", line 32, in <module>
    main()
  File "Main.py", line 21, in main
    tweet = got.manager.TweetManager.getTweets(tweetCriteria)[0]
IndexError: list index out of range

Ie. there are no tweets to return but I am sure that some tweets are. This is happening even on your program with the second query 

    tweetCriteria = got.manager.TweetCriteria().setQuerySearch('europe refugees').setSince("2015-05-01").setUntil("2015-09-30").setMaxTweets(1)
    tweet = got.manager.TweetManager.getTweets(tweetCriteria)[0]

**Comment by mcalistj** [comment]
Ooo and it's working again. But just out of curiosity has Twitter ever blocked your searches/queries?

**Comment by Jefferson-Henrique** [comment]
Hello, not that I remember it, but generally my tests are small.

**Comment by aashanand** [comment]
Now I am experiencing an issue similar to the above. My output from running main.py:

> Example 1 - Get tweets by username [barackobama]
> Username: BarackObama
> Retweets: 200
> Text: This is ityour last chance to win a free trip to Chicago to meet James Taylor: http:// ofa.bo/c5pK pic.twitter.com/y8BYvl0HIb
> Mentions: 
> Hashtags: 
> 
> Traceback (most recent call last):
>   File "main.py", line 32, in <module>
>     main()
>   File "main.py", line 21, in main
>     tweet = got.manager.TweetManager.getTweets(tweetCriteria)[0]
> IndexError: list index out of range

**Comment by mcalistj** [comment]
Twitter doesn't like scrappers. Have a  look at the robots.txt file
https://twitter.com/robots.txt. I think they actually sell some of their
data now since they've restricted their ip. So they'll block your ip if
they detect that you exceed a certain amount of requests.
