### ISSUE TITLE
Urllib2 not parsing the tweets

### ISSUE THREAD

**Issue by feniciu** [Jefferson-Henrique/GetOldTweets-python#31]
Hello,

I have a difference between result from the url :
https://twitter.com/i/search/timeline?f=tweets&q=%20since%3A2014-01-01%20%23axa%2B%23environment&src=typd&max_position=

And the JSONResponse below:
{"min_position":"TWEET--","has_more_items":false,"items_html":"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n","new_latent_count":0,"focused_refresh_interval":30000}

Do you experience the same issue ?

It seems that it could be due to the Internet Service Provider but I dont understand why ?

Fen

**Comment by Jefferson-Henrique** [comment]
Until now I didn't get that error, it happens to you all the time? which arguments are you using?
