### ISSUE TITLE
another dummies question 

### ISSUE THREAD

**Issue by johnsonfx** [Jefferson-Henrique/GetOldTweets-python#33]
Hey there, i'm new to python but i'd like to use this package and learn with experience. 

I typed `python Exporter.py --username "barackobama" --since 2015-06-01 --until 2016-02-01 --maxtweets 1000\n`

but i get this error: 

Traceback (most recent call last):
  File "Exporter.py", line 79, in <module>
    main(sys.argv[1:])
  File "Exporter.py", line 75, in main
    outputFile.close()
UnboundLocalError: local variable 'outputFile' referenced before assignment

What have i not done / done wrongly? Sorry if this is a beginner's question. Appreciate your help.

**Comment by MatHatter** [comment]
Remove the \n and you will get your results.
