### ISSUE TITLE
Badly chosen separator for csv

### ISSUE THREAD

**Issue by Vichoko** [Jefferson-Henrique/GetOldTweets-python#36]
Using ';' as separator is a bad decision because lots of tweets have ';' in their text section, and `.csv` parsers get confused because of that.

I had scripts running for days gathering tweets (.csv) and now i want to use them with R i have my data.frames bad formatted. I've lost hours of data cleaning and until now i can't even parse this csv files!

Any idea? I can't start gathering the data again because i need it for tomorrow so i'm trying to figure a way to clean this data.

**Comment by lucahammer** [comment]
The problem isn't the separator but quotes in tweets. They need to be double quoted in the .csv file.

**Comment by 9mm** [comment]
Agreed, what a total mess.

**Comment by 9mm** [comment]
This tool helped immensely

http://www.convertcsv.com/csv-to-csv.htm

**Comment by chandrasg** [comment]
Hi @9mm @lucahammer Any fix for this issue for the case where the data has already been collected?
