### ISSUE TITLE
Working with Python 3.5?

### ISSUE THREAD

**Issue by Humma4** [Jefferson-Henrique/GetOldTweets-python#38]
Hi,

first of all thank you for creating and sharing this module. I'm working on a project that requires specific tweets, and getting them only in the current week would take way to long, so I tried to take advantage of your solution. I'm using Python 3.5, and I unfortunately can't get it to work. I've got the requirements installed and I've also changed all of the print statements to match the new standard. 

If I copy the contents of the got3 folder to the main directory and run the exporter, I receive the following error: "attempted relative import beyond top-level package". The line that's causing this problem is the following: "from .. import models" (in TweetManager). 

Has anyone been able to use the script with Python 3.5 and would please help me out to get it working? Thanks in advance.

**Comment by Humma4** [comment]
Hi,

sorry about this post... I was only supposed to replace the ".." with "got3" and the script now successfully runs. I'm new to importing and using custom packages/libraries. I haven't been able to test it yet but I'll do it later today. Thanks again for sharing your work!

**Comment by phaerus** [comment]
Have you thought of just using a Python 2.x virtual environment? You can have a .Sh script activate that then run the script etc

**Comment by Humma4** [comment]
I've actually managed to get it working with 3, so I don't think that'll be necessary for now. Thanks for the reply.
