### ISSUE TITLE
Issue with fetching user timeline for longer periods

### ISSUE THREAD

**Issue by Sindhu-Kiranmai** [Jefferson-Henrique/GetOldTweets-python#39]
Hey, 
I've been facing these two issues consistently. Any help in fixing/understanding these will be highly appreciated. 
1. Tweets that appear from query search results are missing in the corresponding user timelines. This happens even after setting the topTweets to "False".
2. This issue has previously been posted. Getting user timeline for a longer time period, say 2-3 years results in an empty .csv file. Sometimes, it runs for a couple of months and terminates. Is this an ISP issue? I've tried reducing the time period to a month, a day but it still fails.

**Comment by chandrasg** [comment]
Hi @Sindhu-Kiranmai 

This looks like an ISP issue - I faced a similar problem but when trying to pull multiple timelines..
