### ISSUE TITLE
Get tweets by query search bound range fails

### ISSUE THREAD

**Issue by swatisaoji1** [Jefferson-Henrique/GetOldTweets-python#4]
This is a very useful piece of code. Great work .
I am looking forward to use the code for one of the data mining project at school.

I downloaded the python code and ran the samples. But the Get tweets by query search/ username  bound range fails

The same query works in the Java version of this project. I was wondering if I am missing something?

**Comment by Jefferson-Henrique** [comment]
Humm, thank you. Can you reply me with what configuration (querySearch / username etc..) you have used? Another thing, did you try the same query in twitter, to see if you get different results?

**Comment by dovalioglu** [comment]
I am also using your code to collect tweets for my big data assignment; however, every time I use the bound range it gives me an empty output_got.csv file. The configuration I use is: python Exporter.py --since 2014-01-01 --until 2014-12-31 --querysearch 'suriyeli'

Thanks again, this code helped me a lot!

**Comment by Jefferson-Henrique** [comment]
Hello @dovalioglu, I have found a weird behavior from twitter when you try these bound dates. Take a look at [Twitter Search](https://twitter.com/search?q=since%3A2014-01-01%20until%3A2014-01-10&src=typd). We get a "invalid query" hahaha and I don't know why yet.

**Comment by Jefferson-Henrique** [comment]
Hello @dovalioglu, take a look at the new version that I have committed and give some feedback if the problem is still there for you, my tests are ok.

**Comment by swatisaoji1** [comment]
Thank you Jefferson , I should be able to try the code in a week or two I will update you . Thanks

**Comment by swatisaoji1** [comment]
It working now  :+1:

**Comment by swatisaoji1** [comment]
Nope the issue stays.  with example 2 and 3

**Comment by swatisaoji1** [comment]
Same issue is being discussed here [https://github.com/Jefferson-Henrique/GetOldTweets-python/issues/8]
