### ISSUE TITLE
Getting tweets for locked accounts that you follow

### ISSUE THREAD

**Issue by aashanand** [Jefferson-Henrique/GetOldTweets-python#5]
Example scenario: I follow a user on twitter but their account is locked. Therefore I can see their tweets but cannot use the TweetManager to export them. Do you have any strategies to allow TweetManager to authenticate into my account before getting the JsonResponse?

**Comment by Jefferson-Henrique** [comment]
Hello, in this moment I don't have, some tweets are not indexed by twitter so you can't see in advanced search but you can see if you directly at a user's timeline
