### ISSUE TITLE
Showing very less number of tweets

### ISSUE THREAD

**Issue by Prakash2403** [Jefferson-Henrique/GetOldTweets-python#50]
I just searched for #Raees, but it gave only 268 results. Same search with tweepy library gave 1012 results in 10 minutes.

**Comment by Jefferson-Henrique** [comment]
Hi @Prakash2403, some tweets are not indexed by Twitter through advanced search, the proposal of GOT is to mimic that search, so unfortunately if gets its bottlenecks too.
