### ISSUE TITLE
Get all tweets which mention a particular user

### ISSUE THREAD

**Issue by charu102** [Jefferson-Henrique/GetOldTweets-python#51]
I am trying to get tweets which are addressed to a particular user, say Barack Obama. I tried queryseach and username method, with the parameter as " @BarackObama", but some tweets were missing in the csv file. So, could you tell me the proper way to do this?

**Comment by Jefferson-Henrique** [comment]
Hello @charu102, some tweets are not indexed by twitter on the general advanced search, if you try there you will see that some tweets are missing, but if you open a user's page you will probably see more. A possilibity is to do a special search if you are looking for a specific user, and look only on his timeline.
