### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by risher1114** [Jefferson-Henrique/GetOldTweets-python#52]
May I ask how to use these codes? I have no background in programming, but I'm doing a project on this topic. So after I unzip these files,  which one I should use.  The "main.py"? Can anyone help me with this?

**Comment by mehdismh24** [comment]
@risher1114 Install python 2.7 and dependencies(requeriments.txt) on your machine and run Main.py using python.exe after unziping.

**Comment by saitam1** [comment]
1. Install lxml (Version 3.5) & pyquery Version 1.2.10):
pip3 install lxml==3.5.0
pip3 install pyquery==1.2.10

2. Download GetOldTweets-python and copy the folder got3 (or "got" if you use Python 2.7) into you site packages folder:
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages
This is on MacOS, on Windows or Linux you have to find out. Just start Python and print the following line: import site; site.getsitepackages()

3. Run Python and use it. You can find examples in Main.py, I give you one here:
```
import got3

tweetCriteria = got3.manager.TweetCriteria().setQuerySearch("Michael Jackson").setMaxTweets(1)
tweet = got3.manager.TweetManager.getTweets(tweetCriteria)[0]

print(tweet.id)
print(tweet.username)
print(tweet.text)
```
print(tweet.date)

**Comment by risher1114** [comment]
Thank you so much.....

2017-02-02 6:26 GMT-05:00 saitam1 <notifications@github.com>:

**Comment by sapanbadjatiya02** [comment]
This was really helpful in extracting the tweets. 
But I have to extract these tweets and perform some analysis. I want to structure these tweets into a Pandas data frame. How should I use this data in Pandas. I was thinking to add this tweet data into MongoDB and then use it into Pandas. Can you provide some suggestion?

**Comment by rushatrai** [comment]
@sapanbadjatiya02 I don't think you need to export to MongoDB. Just search up on how to add items to (or create) a Pandas dataframe, I think that should be sufficient.

**Comment by modatamoproblems** [comment]
@sapanbadjatiya02 try this

#import got and set tweetCriteria and Tweet
import got3
tweetCriteria = got3.manager.TweetCriteria().setQuerySearch("Trump").setMaxTweets(1)
tweet = got3.manager.TweetManager.getTweets(tweetCriteria)[0]

'''
use enumerate to create a new list by index
this avoids the issue of nested lists and only being able to view one observation at a time
'''
for i in enumerate(tweet):
    username_list=[]
    i=0 
    while i <len(tweet):
        username_list.append(tweet[i].username)
        i +=1
for i in enumerate(tweet):
    date_list=[]
    i=0 
    while i <len(tweet):
        date_list.append(tweet[i].date)
        i +=1
for i in enumerate(tweet):
    favorites_list=[]
    i=0 
    while i <len(tweet):
        favorites_list.append(tweet[i].favorites)
        i +=1
for i in enumerate(tweet):
    text_list=[]
    i=0 
    while i <len(tweet):
        text_list.append(tweet[i].text)
        i +=1
#create pandas data frame
import pandas as pd  
twitter_df = pd.DataFrame()
twitter_df['user']  = username_list
twitter_df['date']  = date_list
twitter_df['favorites']  = favorites_list
twitter_df['text']  = text_list

'''
You can ad/substitute using the following attributes and same format: 
id (str)
permalink (str)
username (str)
to (str)
text (str)
date (datetime) in UTC
retweets (int)
favorites (int)
mentions (str)
hashtags (str)
geo (str)
'''

**Comment by sapanbadjatiya02** [comment]
Thank you so much
I will try this out.
