### ISSUE TITLE
getting toptweet for a given time range

### ISSUE THREAD

**Issue by firhatnawfanh** [Jefferson-Henrique/GetOldTweets-python#53]
using it with --toptweet returns a lot of not really top one with 0 retweet and 0 like each with a gap of several second with the next row. How can one isolate only n most-toppest-tweet :) for each day though? instead of having to get ~560-630 tweet to find one.

because setting since and until is not enough, setting those parameter to get a monthly data of 100 obs will only return data from the first day only

**Comment by Jefferson-Henrique** [comment]
Hello @firhatnawfanh, top tweets are retrieved from what Twitter puts on the Top results bar, in your case you want the popular ones, I don't know a way to directly filter thoses tweets.
