### ISSUE TITLE
Error caused by setUntil() --> Only certain dates work, others do not

### ISSUE THREAD

**Issue by saitam1** [Jefferson-Henrique/GetOldTweets-python#54]
When using `setUntil()`, only a few dates work, others return this error:
`lxml.etree.ParserError: Document is empty`
This is my code:
```
max_tweets = 20
tweetCriteria = got3.manager.TweetCriteria().setUntil("2017-02-02").setQuerySearch("bitcoin").setMaxTweets(max_tweets).setLang(Lang="en")
for i in range(max_tweets):
    tweet = got3.manager.TweetManager.getTweets(tweetCriteria)[i]
    print(tweet.text)
    print(tweet.id)
    print(tweet.username)
    print(tweet.date)
```

Here is a little list of dates which work or not:
2017-02-05 error
2017-02-04 error
2017-02-03 ok
2017-02-02 error
2017-02-01 ok
2017-01-31 error
2017-01-30 ok
2017-01-29 ok
2017-01-28 error
2017-01-26 error
2017-01-25 ok

Also when I change the `max_tweets` to `> 20` I get the same error!
Anybody an idea what happens here? Many thanks in advance.

**Comment by Jefferson-Henrique** [comment]
Hi, can you check on default got's folder (phython 2.7)? I don't give a expressive support for python 3+ and I a few improvements were done in the default implementation.
