### ISSUE TITLE
Not able to fetch tweets

### ISSUE THREAD

**Issue by IamAmar** [Jefferson-Henrique/GetOldTweets-python#56]
I ran the given code yesterday and it successfully fetched all the tweets between specific dates for the mentioned tags however i have below concerns, please let me know your comments:

1. Are these the entire tweets for the specified interval( or is there any limit for a calendar day?)
2. When I am running the same script again with updated tags, I am not getting even a single tweet, please let me know the reason for this?

Thanks!

**Comment by Jefferson-Henrique** [comment]
Hello @IamAmar,

1) Not the entire tweets, Twitter doesn't index all tweets to be searched by advanced search (got mimic this feature), so a few tweets are lost. If you are looking for tweets from a specific user it easier no notice that.

2) I don't which tags you have changed, but some people frequently report issues with ISP when searching using GOT.
