### ISSUE TITLE
Tweets extraction limit?

### ISSUE THREAD

**Issue by uditsharma29** [Jefferson-Henrique/GetOldTweets-python#58]
What is the limit to the maximum number of tweets that can be extracted and what is the maximum time duration that can be chosen, I am trying to extract 1000 tweets between 1 month period (3 years old) but I am ending up with only 1 tweet. How to manipulate the code to meet the expected results?

**Comment by Jefferson-Henrique** [comment]
Hello @uditsharma29, maybe you are facing ISP issues, can you share your query? I could run here to check if I get all the results.
