### ISSUE TITLE
Getting Usertimeline

### ISSUE THREAD

**Issue by Sindhu-Kiranmai** [Jefferson-Henrique/GetOldTweets-python#59]
While using the following query to get twitter timeline by username (python Exporter.py --username "barackobama" --since 2015-09-10 --until 2015-09-12 --maxtweets 0) the output file includes tweets by a different username. Upon inspecting the webpage on twitter, I believe re-tweets and mentions which appear on one's timeline are also being crawled as belonging to the user. Does the crawler differentiate between the tweets on one's timeline? Thanks

**Comment by Jefferson-Henrique** [comment]
Hello @Sindhu-Kiranmai, it doesn't differentiate, you can try to do the same query on the Twitter Advanced Search [here](https://twitter.com/search-advanced) to check if you see the same results as GOT.
