### ISSUE TITLE
Problems with command shell

### ISSUE THREAD

**Issue by ViLu206** [Jefferson-Henrique/GetOldTweets-python#6]
Hello,
I am trying to save the tweets as a csv file. But I receive just Syntaxerror in the command shell.

```
>>> python Exporter.py -h
SyntaxError: invalid syntax
```
I use Python 2.7.11

The next question is... I receive just 1 Tweet. I am a beginner with python and I dont Know wich numbers needs to be changed.

Thanks.

**Comment by Jefferson-Henrique** [comment]
![image](https://cloud.githubusercontent.com/assets/1596511/14541686/92ce9932-0261-11e6-9b2f-996511c5ea43.png)

Hello, it is weird, are you inside Python interpreter? If yes this is the problem, look at how I have used the command in the attached file.

**Comment by ViLu206** [comment]
Thanks for your help. :)
I have another question. I try get all tweets about some companys from the last month. But i receive from a few companys just the last month or just 20 posts.

**Comment by Jefferson-Henrique** [comment]
Hello @ViLu206, are you still facing this problem? can you share the criterias that you have used?
