### ISSUE TITLE
Possibility of multiple queries 

### ISSUE THREAD

**Issue by karlsf** [Jefferson-Henrique/GetOldTweets-python#65]
First of all, thanks for this.

Is it possible to query multiple keywords in the same call?

On their site it is possible through: https://twitter.com/search?l=&q=apple%2C%20iphone%2C%20ipod%2C%20macbook&src=typd

Thanks again

**Comment by Jefferson-Henrique** [comment]
Hello, you can do anything that advanced search on twitter allows, so it is possible to query multiple ones =D.
