### ISSUE TITLE
Cannot run the Exporter.py

### ISSUE THREAD

**Issue by ivanbambam1986** [Jefferson-Henrique/GetOldTweets-python#66]
Hi everyone,

I am practically new in Python, I have follow several instructions on how to run python projects and all that stuff. But I have a final issue that I cannot solve and is making my mind blow.

I have tested the project from the Python IDLE and have done some tests from the Main.py and everything is working on, but when I am trying to use the exporter.py from the windows shell with python Exporter.py --username "barackobama" --maxtweets 10 I received and error that says: "You must pass some parameters. Use -"h" to help."

Now I dont know what I am doing wrong, I tried to understand the code in the Exporter.py file and I think is not passing from line 7 but I dont know why... anyone that could help me?

**Comment by ivanbambam1986** [comment]
I fixed the problem, so I will close this issue..

**Comment by Wasiat** [comment]
Hi  ivanbambam1986
I am facing the same problem. How you solved the problem? I cant run the Exporter.py script to get tweets. Please help me.

**Comment by iram01** [comment]
same problem,unable to run Exporter.py script

**Comment by ghost** [comment]
same problem,how to run the Exporter.py script?

**Comment by marquisvictor** [comment]
Hi @iram01 I worked on a twitter data mining project sometime in jULY and i ran into the same issue, I resolved it by optimizing and modifying an already modified version of this code by Dmitri Mottl. 

KInd find attached to this message a link to my Github repository housing my optimised and modified version of this code. Works like magic. 
Thank me Later :)

https://github.com/marquisvictor/Modified-GetOldTweets3

**Comment by ghost** [comment]
Thanks Sir for reply,now i tried
https://github.com/marquisvictor/Modified-GetOldTweets3
I got two errors -cant find '__main__' module in Modified-GetOldTweets3
second error in code of bin\GetOldTweets3.py and tests\GetOldTweets3.py in
raise-no exception reraise

**Comment by marquisvictor** [comment]
@iram01 Please make sure to follow the readme instructions to the letter. I am positive you won't have any issues downloading backdated timeline tweets. 

I still used it two nights ago.
