### ISSUE TITLE
Get tweets by query search

### ISSUE THREAD

**Issue by bkaraoez** [Jefferson-Henrique/GetOldTweets-python#7]
Hello,
Firstly the project is perfect thank you. 
I have a problem; I'm using Example 2 but as result l got only one tweet. Should I change something to get all tweets for a keyword and a given time period?

**Comment by Jefferson-Henrique** [comment]
Thanks @bkaraoez, sorry for my late response. Well, have you try to use "setMaxTweets" with other values?

**Comment by Ritanjali-Panigrahi** [comment]
Hello,
Thank you for sharing the code, it helped me a lot. I have one query: how to write the querysearch if I want to search two keywords at once, for example --querysearch 'one' OR 'two'
