### ISSUE TITLE
since and until filter is not working!

### ISSUE THREAD

**Issue by batuhaniskr** [Jefferson-Henrique/GetOldTweets-python#70]
querysearch with since and until when filter is not insert data, saved file.
Example:

python Exporter.py --querysearch "keyword" --since 2016-07-16 --until 2016-07-17

**Comment by Jefferson-Henrique** [comment]
Hi @batuhaniskr, what did you get? I tried your query and it worked.

**Comment by batuhaniskr** [comment]
It was not working when I posted. It's working right now. 

I think it's probably change in Twitter's source code. 

Thanks!

**Comment by Jefferson-Henrique** [comment]
Nice to hear it!
