### ISSUE TITLE
bound dates suddenly not working

### ISSUE THREAD

**Issue by tangjienan** [Jefferson-Henrique/GetOldTweets-python#8]
Hello:

i tried the last example today and it does not work anymore.It returned 0 tweets.  Everything was fine yesterday so do you know what the problem is?

Thank you

**Comment by chriskao** [comment]
Experiencing the same issue.

**Comment by Jefferson-Henrique** [comment]
Humm, it is weird @tangjienan, maybe you get a temporary empty response from twitter, are you still facing this problem? and you @chriskao?

**Comment by APUnatto** [comment]
Hi, @Jefferson-Henrique . I also have the same problem. The project was working fine the other day and suddenly did not work anymore. I hope you can fix this issue. Thank you very much.

**Comment by chriskao** [comment]
It worked again today!

On Mon, May 16, 2016 at 4:13 PM, Jefferson Henrique <
notifications@github.com> wrote:

> Humm, it is weird @tangjienan <https://github.com/tangjienan>, maybe you
> get a temporary empty response from twitter, are you still facing this
> problem? and you @chriskao <https://github.com/chriskao>?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Jefferson-Henrique/GetOldTweets-python/issues/8#issuecomment-219575996>
>



-- 
Stanford University Class of 2014
Symbolic Systems / Human Computer Interaction
My Site <http://www.yuchunkao.com> | Blog
<http://calligraphydance.wordpress.com/> | LinkedIn
<http://www.linkedin.com/pub/christina-kao/2a/9b/668> | 650-391-6402

**Comment by APUnatto** [comment]
@chriskao really? I still could not get it to work. Did you change anything?

**Comment by chriskao** [comment]
No I didn't, not sure what made it work again.

On Thu, May 19, 2016 at 9:11 PM, APUnatto <notifications@github.com> wrote:

> @chriskao <https://github.com/chriskao> really? I still could not get it
> to work. Did you change anything?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Jefferson-Henrique/GetOldTweets-python/issues/8#issuecomment-220513076>
>



-- 
Stanford University Class of 2014
Symbolic Systems / Human Computer Interaction
My Site <http://www.yuchunkao.com> | Blog
<http://calligraphydance.wordpress.com/> | LinkedIn
<http://www.linkedin.com/pub/christina-kao/2a/9b/668> | 650-391-6402

**Comment by APUnatto** [comment]
Did you run the Main.py? Which tool did you use to run it? Thank you.

**Comment by chriskao** [comment]
I've only been using the command line queries.

On Thu, May 19, 2016 at 9:17 PM, APUnatto <notifications@github.com> wrote:

> Did you run the Main.py? Which tool did you use to run it? Thank you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Jefferson-Henrique/GetOldTweets-python/issues/8#issuecomment-220513604>
>



-- 
Stanford University Class of 2014
Symbolic Systems / Human Computer Interaction
My Site <http://www.yuchunkao.com> | Blog
<http://calligraphydance.wordpress.com/> | LinkedIn
<http://www.linkedin.com/pub/christina-kao/2a/9b/668> | 650-391-6402

**Comment by mali23** [comment]
Hi,
       Great work, thank you for sharing.
But i am having the same problem the code was working till yesterday and now its not returning me anything, whenever i run the command line query it shows something like 
searching......
Done. Output file generated "output_got.csv"

with no tweets in it. my query is something like.
"python Exporter.py --since 2016-01-01 --until 2016-05-20 --querysearch 'MERS-CoV'"

Am i doing something wrong or is it something else?

Thank you

**Comment by bcn1161** [comment]
Hi, 
I'm experiencing this same problem. It worked perfectly yesterday, but when I ran the same code today, it wouldn't fetch tweets with a set time range. Everything else is fine. What do you think could be the possible reason to this? Thanks! @Jefferson-Henrique

**Comment by Jefferson-Henrique** [comment]
Hello @mali23  and @bcn1161, did you test it with the last version (the one that logs a message every 100 tweets)? Besides that when you face this problem can you check what Twitter shows after you use [Advanced Search](https://twitter.com/search-advanced)? Maybe there it isn't showing good as well. Thanks for your replies, I have discovered some issues because of you all on this thread.

**Comment by Jefferson-Henrique** [comment]
It really weird, I don't know yet what causes this inconsistent behavior because when I am testing it works hahah

**Comment by bcn1161** [comment]
It's working now! @Jefferson-Henrique I have no idea why...

**Comment by novikesumaningtyas** [comment]
Hai @Jefferson-Henrique , thanks for your great code, its really help me.
But yes, i'm facing the same problems, it worked perfectly when the early time i tried, i got the tweets from 2013, but when I ran the same code with a same set time range today, i got nothin. But if i change the range time from just last week or a few days from now (since : few days ago, until :now), it got me the tweets.

Is there any way twitter know and blocked me to access their old tweets again?
or there might be any answer for this?
Thanks lot!

**Comment by Jefferson-Henrique** [comment]
Humm thanks for your reply @novikesumaningtyas, can you test again? there is a new apprach now to handle twitter requests, lets see if this will help you.

**Comment by novikesumaningtyas** [comment]
Hai @Jefferson-Henrique thanks for your reply and update, yes it works after i pull the new one. Wonderful work!

**Comment by shadigkh** [comment]
I'm having the same problem.  I got 10000 tweets from 2012 yesterday. But, it returns 0 tweets just the morning after.

**Comment by Jefferson-Henrique** [comment]
Hello @shadigkh, can you get the last version and test it again?

**Comment by shadigkh** [comment]
Hello  @Jefferson-Henrique, sorry for such a dumb question. I don't know much about Git. So, what do you mean by the last version? The "got" package hasn't been updated since 19 days and that's the one I'm using right now.

**Comment by Jefferson-Henrique** [comment]
That is ok @shadigkh, please download it again, it is from 19 days ago because I have accepted an old pull request, but in fact I did this yesterday, so this update can help you.

**Comment by shadigkh** [comment]
Thank you  @Jefferson-Henrique for the details. I downloaded and used the new version. But, I don't get any results when I use dates. It works perfectly without the dates though.

**Comment by novikesumaningtyas** [comment]
hai @shadigkh , just want to share my experience when i used the previous package, i tried to change my internet source, like i always use home wifi then change my internet to another wifi or from mobile phone provider, i can get old tweet again from 2013, idk why maybe it got somthin with ISP

**Comment by shadigkh** [comment]
Thank you @novikesumaningtyas. As you suggested, I'm using a different ISP now and it's working!

**Comment by jdhurwitz** [comment]
I'm having this issue too. Is there any way to fix it other than switching to a different ISP? I noticed that it worked on my school campus but not at home...
