### ISSUE TITLE
ASCII Codec issue

### ISSUE THREAD

**Issue by psychemedia** [Jefferson-Henrique/GetOldTweets-python#9]
Running under Py 2.7 throws an ASCII encoding issue on the file write if it hits a character it doesn't like:

```
Traceback (most recent call last):
  File "Exporter.py", line 66, in <module>
    main(sys.argv[1:])
  File "Exporter.py", line 56, in main
    outputFile.write('\n%s;%s;%d;%d;"%s";%s;%s;%s;"%s";%s' % (t.username, t.date.strftime("%Y-%m-%d %H:%M"), t.retweets, t.favorites, t.text, t.geo, t.mentions, t.hashtags, t.id, t.permalink))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xeb' in position ...
```

**Comment by Jefferson-Henrique** [comment]
Hello @psychemedia, I am using Py 2.7 too, can you share which query you have used? I can update the code to remove this character, I have removed some like on this line **re.sub(r"[^\x00-\x7F]", "")**.

**Comment by psychemedia** [comment]
I think you need to handle the UTF properly rather than fudging?

**Comment by Jefferson-Henrique** [comment]
Yeah, I made some changes on this way now, take a look when you can, thanks for your feedback.
