### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by TeriVolta** [Jefferson-Henrique/GetOldTweets-python#93]
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    main(since, until, filename)
  File "main.py", line 50, in main
    for tweet in got.manager.TweetManager.getTweets(tweetCriteria):
  File "/home/taras/Desktop/freelance/twitter/GetOldTweets-python/got/manager/TweetManager.py", line 40, in getTweets
    retweets = int(tweetPQ("span.ProfileTweet-action--retweet span.ProfileTweet-actionCount").attr("data-tweet-stat-count").replace(",", ""));
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by Jefferson-Henrique** [comment]
Hi @TeriVolta, are you using Python2.7 or 3?

**Comment by TeriVolta** [comment]
Python 2.7

**Comment by TeriVolta** [comment]
can 'try'
 help here?

**Comment by hariskr** [comment]
Have you resolved this issue? I guess try could help avoid the error message, but it still won't get the tweets... Would breaking up the data collection into smaller time windows help?
